// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC40pc81fuSWrnvkgul2bRyqcRNtR9p2fU',
    appId: '1:275520285491:web:9d19f6d8ce93cfe0316c46',
    messagingSenderId: '275520285491',
    projectId: 'virtualhealth-287',
    authDomain: 'virtualhealth-287.firebaseapp.com',
    databaseURL: 'https://virtualhealth-287-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'virtualhealth-287.appspot.com',
    measurementId: 'G-TM0KGJGPG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrYg2xcdfuBtgQ7SVCWoP5DD3yonhflsQ',
    appId: '1:275520285491:android:61dab2a06577167c316c46',
    messagingSenderId: '275520285491',
    projectId: 'virtualhealth-287',
    databaseURL: 'https://virtualhealth-287-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'virtualhealth-287.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKDZ0h110gD4KxRWna1HgPWjkiiQAfHFo',
    appId: '1:275520285491:ios:658fbe49b80a94e3316c46',
    messagingSenderId: '275520285491',
    projectId: 'virtualhealth-287',
    databaseURL: 'https://virtualhealth-287-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'virtualhealth-287.appspot.com',
    androidClientId: '275520285491-h05a4i6md397oprkl9htas10l0tkakc0.apps.googleusercontent.com',
    iosClientId: '275520285491-b7sl38ps8o73bs4njhj7h9hclt5iubdp.apps.googleusercontent.com',
    iosBundleId: 'com.example.virtualhealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKDZ0h110gD4KxRWna1HgPWjkiiQAfHFo',
    appId: '1:275520285491:ios:658fbe49b80a94e3316c46',
    messagingSenderId: '275520285491',
    projectId: 'virtualhealth-287',
    databaseURL: 'https://virtualhealth-287-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'virtualhealth-287.appspot.com',
    androidClientId: '275520285491-h05a4i6md397oprkl9htas10l0tkakc0.apps.googleusercontent.com',
    iosClientId: '275520285491-b7sl38ps8o73bs4njhj7h9hclt5iubdp.apps.googleusercontent.com',
    iosBundleId: 'com.example.virtualhealth',
  );
}
